name: json_serializable_generic
description: A simple library to add json serializable behavior to a class
version: 1.0.0
homepage: https://github.com/jonathanots/dart_json_serializable
repository: https://github.com/jonathanots/dart_json_serializable

environment:
  sdk: '>=2.15.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
